services:
  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m sum_service.grpc.server
    ports:
      - "50051:50051"
    networks:
      - sum-network
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.socket().connect(('localhost', 50051))"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  envoy-proxy:
    image: envoyproxy/envoy:v1.28-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
    networks:
      - sum-network
    depends_on:
      - grpc-server

  websocket-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m sum_service.websocket.server
    ports:
      - "8765:8765"
    depends_on:
      grpc-server:
        condition: service_healthy
    networks:
      - sum-network
    environment:
      - GRPC_HOST=grpc-server
      - GRPC_SERVER_PORT=50051

networks:
  sum-network:
    driver: bridge 