# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sum.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsum.proto\x12\x03sum\"\x1c\n\nSumRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1d\n\x0bSumResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x41\n\nSumService\x12\x33\n\x0c\x43\x61lculateSum\x12\x0f.sum.SumRequest\x1a\x10.sum.SumResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sum_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUMREQUEST']._serialized_start=18
  _globals['_SUMREQUEST']._serialized_end=46
  _globals['_SUMRESPONSE']._serialized_start=48
  _globals['_SUMRESPONSE']._serialized_end=77
  _globals['_SUMSERVICE']._serialized_start=79
  _globals['_SUMSERVICE']._serialized_end=144
# @@protoc_insertion_point(module_scope)
